### ISSUE TITLE
Every command yields "HTTP ERROR 500"

### ISSUE THREAD

**Issue by cjforzero** [rene-s/Seafile-PHP-SDK#9]
I apologize for the trouble I may cause you. But if I want to execute some commands, such as create the directory it  return "HTTP ERROR 500" even if  I can get the list of available libraries successfully .

**Comment by rene-s** [comment]
Hello cjforzero, it's no trouble at all... if you could provide some more information such as 

- Which call are you making?
- Do you have permissions to create a new directory?
- Do you have permissions to read the directory?
- Does the Seafile server work OK otherwise?
- Did you obtain an API token from the server and has it been stored correctly?
- Which branch or tag of the Seafile-PHP-SDK are you using?
- Which PHP version are you using?
- What is the version of the Seafile server you are using?
- Is OS you are using Seafile-PHP-SDK on 32 bits or 64 bits?

Regards
Rene
